#ifndef _SYSCALL_H_
#define _SYSCALL_H_
/* DO NOT modify this file directly, This file was generated by gen_sys.py.*/

typedef int (*syscall_fn_ptr)();
	#define SYS_exit		0
	#define SYS_fork		1
	#define SYS_read		2
	#define SYS_write		3
	#define SYS_open		4
	#define SYS_close		5
	#define SYS_waitpid		6
	#define SYS_creat		7
	#define SYS_link		8
	#define SYS_unlink		9
	#define SYS_execve		10
	#define SYS_chdir		11
	#define SYS_time		12
	#define SYS_mknod		13
	#define SYS_chmod		14
	#define SYS_lchown		15

	extern int sys_exit();
	extern int sys_fork();
	extern int sys_read();
	extern int sys_write();
	extern int sys_open();
	extern int sys_close();
	extern int sys_waitpid();
	extern int sys_creat();
	extern int sys_link();
	extern int sys_unlink();
	extern int sys_execve();
	extern int sys_chdir();
	extern int sys_time();
	extern int sys_mknod();
	extern int sys_chmod();
	extern int sys_lchown();

	syscall_fn_ptr syscall_table[] = {sys_exit,sys_fork,sys_read,sys_write,sys_open,sys_close,sys_waitpid,sys_creat,sys_link,sys_unlink,sys_execve,sys_chdir,sys_time,sys_mknod,sys_chmod,sys_lchown,};

#endif