#ifndef _SYSCALL_H_
#define _SYSCALL_H_
/* DO NOT modify this file directly, This file was generated by gen_sys.py.*/

typedef int (*syscall_fn_ptr)();
	#define SYS_read		0
	#define SYS_write		1

	extern int sys_read();
	extern int sys_write();

	syscall_fn_ptr syscall_table[] = {sys_read,sys_write,};

#endif